export default {
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  LOAD_APP_DATA: 'LOAD_APP_DATA',
  CLEAR_APP_DATA: 'CLEAR_APP_DATA',
  IS_APP_LOADING: 'IS_APP_LOADING',
  UPDATE_PAGE_DATA: 'UPDATE_PAGE_DATA',
  UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
  CLEAR_PAGE: 'CLEAR_PAGE',
  SEND_FORM_DATA: 'SEND_FORM_DATA',
  RECEIVE_AUTH_USER: 'RECEIVE_AUTH_USER',
  RECEIVE_AUTH_ERROR: 'RECEIVE_AUTH_ERROR',
  IS_PAGE_LOADING: 'IS_PAGE_LOADING',
  SET_PAGE_ERROR: 'SET_PAGE_ERROR',
  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG'
};
